params_ai:
  eta: 0.4
  layers:
  - 16
  - 32
  - 32
  - 32
  - 4
params_generation:
  n_generation: 5
  portion: 0.3
  rd: 0.3
  run_type: basic
params_population:
  games_played: 5
  length: 20
